### ISSUE TITLE
Development version still marked as 8.6.9

### ISSUE THREAD

**Issue by fehmud** [asciidoc-py/asciidoc-py2#103]
Hello,
the latest development version outputs the string `8.6.9` as its version.  Shouldn't the version be something like `8.6.10-dev` or something like that?

Commands:

```
asciidoc --version
a2x --version
```

Thanks for your attention.

**Comment by elextr** [comment]
Possibly, though at the moment there is no plan for a 8.6.10 release.

**Comment by aerostitch** [comment]
There's been a lot of changes since 8.6.9. It would be really convenient for the distro that stil use asciidoc like Debian to have a new tag cut just to make it more maintainable. Currently we just add patches to the current release but it doesn't seem sustainable.

**Comment by elextr** [comment]
Given the lack of contributions recently I thought maybe nobody was distributing it any more.

Well, no releases have been made since Stewart left because nobody knows how.  It would be easy to tag it in the repository, but someone has to locate all the strings that need updating in the code and documentation then I believe there is some sort of builder script using AAP (a tool from Brad Moolenaar of vim fame) or is that for you distro folks?  AFAIK the release process isn't automated.

Given that Python 2 lifetime is only guaranteed until 2020 (not stated if thats Jan or Dec 2020 :) and no contributions, this version is not sustainable for long anyway, and doesn't seem worth the effort to find how to make releases of this version.  

The Python 3 port is in the boring tedious process of making all the regression tests pass, see https://github.com/asciidoc/asciidoc3/pull/1 and maybe providing assistance to that process and then the release process for that version is a better use of effort to ensure sustainability.

**Comment by MasterOdin** [comment]
AsciiDoc.py lives on in the https://github.com/asciidoc-py/asciidoc-py repo which is seeing new releases.
