### ISSUE TITLE
a2x uses /usr/bin/env python2

### ISSUE THREAD

**Issue by Ichabond** [asciidoc-py/asciidoc-py2#116]
a2x uses `/usr/bin/env python2` to force the use of python 2. This unfortunately is broken on OS X, as it does not have a python2 symlink anywhere on the system. Changing the current setup to `/usr/bin/env python2.7` should be sufficient.

**Comment by elextr** [comment]
Thats a breakage in the OSX python, you should report it to them, see [PEP 394](https://www.python.org/dev/peps/pep-0394/) for reference.  The python2 command should be available if any version of python 2 is installed.  There are lots of scripts with python2 in them which are not going to be updated.

But since `env` searches PATH you can add a link in any location on PATH and that should make it work.

**Comment by Ichabond** [comment]
Figured as much yeah, but thanks for the confirmation, and the PEP link.
