### ISSUE TITLE
Use friction to get more contributions

### ISSUE THREAD

**Issue by edusantana** [asciidoc-py/asciidoc-py2#16]
Philosophy of [friction](https://github.com/rafalchmiel/friction)

If you want people to use and contribute to your project, you need to start by answering their most basic questions. Friction is a command line script that will check your project for common answers to these questions. Read more at [friction/wiki](https://github.com/rafalchmiel/friction/wiki).

**Comment by elextr** [comment]
I don't think it will help much, the only thing that would be added is CONTRIBUTING, but feel free to submit a suitable example.  Of the other items friction lists as "required":
- has a README, and it also points to the website
- COPYING is a common and allowed synonym for LICENSE
- Asciidoc doesn't need a bootstrap script, a source version just needs to be put somewhere and it will work.  The only dependency is of course Python, but installing that depends on the system and how it accesses the repositories.  I note friction does not install ruby that it needs itself :)  And installing PDF toolchains is also a bad idea without knowing what users want to do with asciidoc since they are very heavy and messy things.
- Asciidoc has tests
- Asciidoc has .gitignore

**Comment by mojavelinux** [comment]
I like the idea of a CONTRIBUTING doc. For a template, see https://github.com/github/markup/blob/master/CONTRIBUTING.md (except in AsciiDoc, of course).

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph
