### ISSUE TITLE
user guide: broken link in section 5.6

### ISSUE THREAD

**Issue by linuxstudio** [asciidoc-py/asciidoc-py2#51]
The document: http://asciidoc.org/userguide.html has a broken link in section 5.6
Specifically, the FOP link points to http://xml.apache.org/fop/ which is not anymore existing. 
I believe that the correct link should be: http://xmlgraphics.apache.org/fop/

**Comment by elextr** [comment]
I get http://projects.apache.org/projects/fop.html as the FOP project site.

Any other suggestions.

Cheers
Lex

**Comment by mojavelinux** [comment]
Both are valid. The project literally has two home pages. I find the
xmlgraphics page more informative.

**Comment by elextr** [comment]
Ok, xmlgraphics is the original page that was linked to, so I guess keep with that

Cheers
Lex

**Comment by elextr** [comment]
Done in Git 1f3b83f933, note this won't update the website until it is re-generated.

**Comment by mojavelinux** [comment]
@elextr Can we get website regeneration setup in Travis CI? (basically to publish to GitHub Pages...which could be a separate repo). I have control of the DNS, so I can easily change where it points. I guess we just need to get the okay from Stuart since he still runs the site technically.

GitHub Pages is super easy to setup, and we can get Travis CI to do the build / publish step to get the generated files into the right repository. If you want to proceed, let's open a dedicated issue.

**Comment by elextr** [comment]
@mojavelinux yes, thats what the plan is, to publish the website from the github sources.  Either github pages or maybe readthedocs.  I know the latter allows multiple versions (eg latest/HEAD and the last release would be good).

It just needs somebody with the time to do it.

**Comment by mojavelinux** [comment]
> It just needs somebody with the time to do it.

In my experience, the first step is having an issue. Then, the people will come :) (or maybe they won't, but they won't come if there's no issue).

**Comment by elextr** [comment]
Let them come https://github.com/asciidoc/asciidoc/issues/52 :)
