### ISSUE TITLE
Create the Asciidoc website directly from the Github sources

### ISSUE THREAD

**Issue by elextr** [asciidoc-py/asciidoc-py2#52]
Currently the Asciidoc website continues to be served from Stuarts server.  It therefore does not get updated as changes are made.

Ideally the website should be generated from the github sources whenever they change and made available using [Github Pages](https://guides.github.com/features/pages/) or maybe [Read the Docs](https://readthedocs.org/).

It would be preferable if docs for the last release and current development head were available.

**Comment by mojavelinux** [comment]
:+1: Thanks for filing the issue @elextr!

**Comment by elextr** [comment]
Skip Read the Docs, it doesn't support asciidoc, unless someone (tm) wants to add an asciidoc backend.

**Comment by mojavelinux** [comment]
It's incubating: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/asciidoc.py

Having said that, it's simple enough to use a static site generator to push published HTML to gh-pages. There are tons of static site generators that can do this, so really any one that has that workflow will do. Some might even support building out sites per version. If anyone would like to recommend the tool choice that satisfies those requirements (preferably Python since this is a Python project), please respond.

**Comment by edusantana** [comment]
If I was going to do this, I would:
- setup a [webhook](https://developer.github.com/webhooks/) at github to get the push event send to a server 
- generate the asciidoc site at the server with [sinatra and ruby](https://developer.github.com/webhooks/configuring/)
- push back to the [gh-pages](https://help.github.com/articles/creating-project-pages-manually/) branch where it will be available as static pages.

**Comment by mojavelinux** [comment]
I find Travis CI to be a very good fit to be that server, though I know
there are other good options as well.

**Comment by mojavelinux** [comment]
Who was working on this again? I ask because it seems that there are files missing from the generated output. The script that generated the current gh-pages branch needs to be updated. See #78.

**Comment by mojavelinux** [comment]
I don't think there's a clear cut choice here. On the one hand, the website should reflect the latest release, which means if the trigger exists, it should be on the tag, not master. However, we would still need a process for allowing changes through that are content updates that do apply to the current version (a broken link, for instance).

The best solution, though perhaps not appropriate here, is to version the website so that you can see the docs per the version you are using, including master. But I don't see us having the resources to make that happen.

**Comment by elextr** [comment]
Yes, like read the docs can be set to show `latest` built from HEAD and a tagged version.

**Comment by sethwoodworth** [comment]
I highly recommend using Travis-CI for this.  Compiling html to the `gh-pages` branch and pushing back to github is a surprisingly clean way to manage updating the site.  The [jekyll-asciidoc-quickstart](https://github.com/asciidoctor/jekyll-asciidoc-quickstart#directions) repo has great instructions about how to make this work together.

I get thrown off every time I follow a asciidoc.org link to google code and would like to help get this updated.

**Comment by mojavelinux** [comment]
:+1:
