### ISSUE TITLE
Cleaner build process for working with git

### ISSUE THREAD

**Issue by apjanke** [asciidoc-py/asciidoc-py2#74]
Hi, AsciiDoc folks,

Is there interest in making a "cleaner" build process, to allow developers to do a full build and test in the source tree in a way that interacts well with Git? I'm starting to work with asciidoc and do some testing, and the build process (which I'm running in order to do end-to-end testing) leaves stuff in the working copy that require manual cleanup.

Here's a specific example. Let's say I did a minor change to `asciidoc.py` and wanted to test it out.

```
$ git status -s
 M asciidoc.py
```

I'll do a build in the source tree with `make`. Then a `make install` (not shown) to deploy the test version, so I can validate that the installation results work as expected. After this, there are several artifacts left over, even after a `make clean`.

```
$ autoconf
$ ./configure --prefix=/tmp/my-asciidoc-test >/dev/null
$ make
Fixing CONF_DIR in asciidoc.py
Fixing CONF_DIR in a2x.py
python a2x.py -f manpage doc/a2x.1.txt
python a2x.py -f manpage doc/asciidoc.1.txt
$ git status -s
 M a2x.py
 M asciidoc.py
?? Makefile
?? config.status
?? configure
?? doc/a2x.1
?? doc/asciidoc.1
$ make clean
rm -f doc/a2x.1 doc/asciidoc.1
$ git status -s
 M a2x.py
 M asciidoc.py
?? Makefile
?? config.status
?? configure
$
```

To get back to a clean repo, I need to manually delete those extra files. And more inconvenient, the in-place `make` processing has added another change to `asciidoc.py` which is mixed in with the actual source change I wanted to do. As a developer, I need to be aware of that, and then manually back out the edit or revert that hunk in `git`.

If I proceed to do testing as described in `INSTALL.txt`, that leaves more stuff in the repo that `make clean` doesn't take care of.

```
$ ./asciidoc.py doc/asciidoc.txt
$ ./tests/testasciidoc.py update &>/dev/null
$ make clean
rm -f doc/a2x.1 doc/asciidoc.1
$ git status -s
 M a2x.py
 M asciidoc.py
?? Makefile
?? config.status
?? configure
?? doc/asciidoc.html
?? doc/latex-filter__1.png
?? doc/latex-filter__2.png
?? doc/latex1.svg
?? doc/latex2.png
?? doc/latex3.svg
```

Could we make a few changes to improve this? Things I'm thinking of:
- Add `Makefile`, `configure`, and `config.status` to `.gitignore`
  - Or even check `configure` in to the repo? It's supposed to be portable and go out as part of the distribution; this would mean casual developers, or people who wanted to install from `HEAD` for testing, wouldn't need Autoconf installed, and could skip a step in the build process.
-  Add a `make distclean` target that will remove `Makefile` and the rest of `configure`'s output
- Instead of fixing `asciidoc.py` and `a2x.py` in-place, make new copies in a `build` directory, which is also in `.gitignore`.
- Add the test outputs to the `make clean` target? Or revise the tests to write to a git-ignored output directory?

I know you can just do `git clean` and `git checkout --` and the like to clean things up, but that's a bit more work, and doesn't interact well with changes you've made and want to keep. And the status output would still be cluttered.

If there's interest, I could do most of these changes myself, since they're simple Makefile or .gitignore changes.

**Comment by elextr** [comment]
@apjanke sure possibly the system should be improved, but I'm not sure its worth it.  

The Python implementation of Asciidoc is not under heavy development any more.  It will be around for a long time since there are many people who have customised system extensions which lock them into this implementation.  But it is Python 2 and there is no sign of anybody being interested in porting or re-implementing it in Python 3 (which would also help fix some of the Unicode issues).  Really only bugfixes are added these days.

But most new development happens on the [Asciidoctor](http://asciidoctor.org/) implementation now.  Asciidoctor is much faster, and uses a better design than the Python implementation.  It was started to provide Asciidoc markup rendering in GitHub, so it was implemented in Ruby and its initial focus was HTML and web technologies, but it is now supporting FOP for PDF and developing its own direct PDF generation capability (still Alpha status).  It does not directly support dblatex, which limits it in some peoples eyes since there is a big difference between the "traditional" rendering of Latex and the "modern" rendering of FOP.  Of course you could just generate the docbook xml and feed it to a2x to use dblatex.  The Asciidoctor devs make a conscious effort to maintain backward compatibility for old documents which is excellent. ( @mojavelinux will correct any errors I made here :smile: )

Here endeth the history lesson.

**Comment by mojavelinux** [comment]
Thanks for that summary @elextr!

> [Asciidoctor] is now supporting FOP for PDF

Actually, since FOP ties into the DocBook toolchain, all either project is doing after the DocBook XML is generated is to wrap the DocBook toolchain. You can still use a2x on the DocBook output from Asciidoctor...or you can use the pure-JVM equivalent fopub. But the state of the art is mostly unchanged in this area.

>  [Asciidoctor is] developing its own direct PDF generation capability (still Alpha status)

We're much, much closer to beta now with the fixes this week. It's very near ready to be a suitable replacement for the DocBook toolchain (specifically the FOP pathway).

> [Asciidoctor] does not directly support dblatex

Thanks to work done recently by Jim Carlson, I'm happy to say it does now. Jim is taking it much further than what was done in AsciiDoc Python, and there may be some compatibility differences, but exciting stuff. See https://vschool.s3.amazonaws.com/manuscripts/389.html.

**Comment by elextr** [comment]
> > [Asciidoctor] does not directly support dblatex
> 
> Thanks to work done recently by Jim Carlson, I'm happy to say it does now. Jim is taking it much further than what was done in AsciiDoc Python, and there may be some compatibility differences, but exciting stuff. See https://vschool.s3.amazonaws.com/manuscripts/389.html.

[technicality alert] I think that supports _Latex_ not _DbLatex_.  

It appears similar to the now defunct Asciidoc Latex backend.   But it appears to have some compatibility issues that would stop a Asciidoc-Latex document also being used for "normal" Asciidoc IIUC.   So how well does a "normal" Asciidoc document render with the Latex backend? 

Speaking of "normal" Asciidoc, that raises the question, what is happening with the standard specification for Asciidoc markup?

( @apjanke sorry to hijack your issue :)

**Comment by mojavelinux** [comment]
> [technicality alert] I think that supports Latex not DbLatex.

Ah, correct. I'm assuming once the LaTeX is generated, then you can use DbLaTeX (but I'm not very well versed in LaTeX, so I may not know what the heck I'm talking about). Having said that, I know it is on Jim's radar to get the whole chain working.

> It appears similar to the now defunct Asciidoc Latex backend.

Yep, that was the original source of inspiriation.

> But it appears to have some compatibility issues that would stop a Asciidoc-Latex document also being used for "normal" Asciidoc IIUC.

This is just a development stage thing. I'm continuing to work with Jim to find the right balance of compatibility. AsciiDoc certainly makes it possible with it's flexible blocks, so I'm sure we'll get there.

> Speaking of "normal" Asciidoc, that raises the question, what is happening with the standard specification for Asciidoc markup?

We've started a repo to start playing around with some grammar / parser code and discuss issues. I've been pinched for time lately, so I haven't been able to do much more, but it's definitely on my radar.

https://github.com/asciidoctor/asciidoc-grammar-prototype

**Comment by apjanke** [comment]
Hijack away; this is good info! I'll have a look at Asciidoctor since that's new to me.

**Comment by edusantana** [comment]
> Ah, correct. I'm assuming once the LaTeX is generated, then you can use DbLaTeX

dblatex works on docbook xml, and with both versions: 4.5 and 5.0.

> [technicality alert] I think that supports Latex not DbLatex. 

Yes, the `asciidoc-latex` will generate Latex code, that you can compile with `pdflatex`.

The are many TeX words out here. From our world, we have `asciidoc` that is a project with "only bugfixes are added these days". And `asciidoctor` where "most new development happens". At the TeX world, we have PDFTeX (only bugfixes) and ConTeXt (new development).

At the moment we can build using ConTeXt and docbook 4.5 (the 5.0 doesn't work) with [dbcontext](http://dblatex.sourceforge.net/example/manual-dbcontext.pdf).

I'm testing many asciidoc toolchains for pdf generation: https://github.com/edusantana/udc-texts-to-compare-asciidoc-toolchains.

**Comment by MasterOdin** [comment]
Decent bit of work has gone into updating `.gitignore` in the https://github.com/asciidoc-py/asciidoc-py to make working in git smoother
